# Generated by Django 3.0.7 on 2020-06-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_category', models.CharField(choices=[('UN', 'Uncategorized'), ('FE', 'Front End Development'), ('BE', 'Back End Development'), ('FS', 'Full Stack Development'), ('MD', 'Mobile Development'), ('DO', 'DevOps'), ('QA', 'Quality Assurance'), ('PM', 'Project Management'), ('UI', 'User Interface'), ('UX', 'User Experience')], default='UN', max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('technologies', models.ManyToManyField(to='api.Technology')),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(to='api.Technology'),
        ),
    ]
